apiVersion: v1
kind: ConfigMap
metadata:
  name: signatrust-config
data:
  server.toml: |
    name = "application"
    tls_cert = ""
    tls_key = ""
    ca_root = ""
    [data-server]
    server_ip = "0.0.0.0"
    server_port = "8080"
    [kms-provider]
    type = "huaweicloud"
    kms_id = "65ccb4d8-cc45-4139-b380-2fcff184ac4f"
    endpoint = "cn-north-4.myhuaweicloud.com"
    project_name = "cn-north-4"
    project_id = "25f40abeecb84d3e90731de258ca71ec"
    username = "freesky-edward"
    password = ""
    domain="freesky-edward"
    [database]
    connection_url = "mysql://test:test@signatrust-database.signatrust.svc.cluster.local:3306/signatrust"
    max_connection = 10
    [encryption-engine]
    keep_in_days = 180
    algorithm = "aes256gsm"
  client.toml: |
    working_dir = "/app/data/"
    worker_threads = 8
    buffer_size = 20480
    [server]
    domain_name = "signatrust.test.osinfra.cn"
    tls_cert = ""
    tls_key = ""
    type = "dns"
    server_name = "signatrust-server-headless.signatrust.svc.cluster.local"
    server_port = "8080"
