apiVersion: v1
kind: Service
metadata:
  name: signatrust-server
spec:
  ports:
    - name: signatrust
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    component: signatrust-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: signatrust-server-headless
spec:
  ports:
    - name: signatrust
      port: 8080
      protocol: TCP
      targetPort: 8080
  clusterIP: None
  selector:
    component: signatrust-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: signatrust-database
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    component: signatrust-database
  type: ClusterIP
